# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e239f7a8f478d850042a600367018525cb8184dc768678fe0ac9e3e974245f0c85dc7855c0b67bb7fb215a75333be0e9f42a99de02e188fb19a52f4556ea03d1

test:
  secret_key_base: 39cf5127fcc8d575daf4cfd9d591fdd6a6646baeaeae2418506516264aecd782900c79a4351d91cbb9f88188a6012690fb64162cf54878d639dce5ba176526fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  secret_key_base: 45cc8ce111727408459d8c4a966c2044288cbf9b1846610e4410040fe40e8c0fa91225cf7d94e794d270001bfb181f7c8a974b2058854acfa29603fee1e67779
